import { EventData } from './event';

export const MOCK_DATA: EventData[] = [
  {
    date: new Date(2020, 5, 10),
    quantity: 3,
    price: 365,
    eventTypeName: 'Liftleie dagpris',
    isExpenseType: true,
    isHoursEventType: false,
    isAdditionalHoursEventType: false,
    isWorkHour: false,
    isApproved: true,
    isRejected: false,
    tasksCount: 2,
    firstTaskStart: new Date(2020, 5, 8),
    lastTaskEnd: new Date(2020, 5, 8),
  },
  {
    date: new Date(2020, 5, 10),
    quantity: 7.5,
    price: null,
    eventTypeName: 'Arbeidstid',
    isExpenseType: false,
    isHoursEventType: true,
    isAdditionalHoursEventType: false,
    isWorkHour: true,
    isApproved: true,
    isRejected: false,
    tasksCount: 2,
    firstTaskStart: new Date(2020, 5, 8, 8),
    lastTaskEnd: new Date(2020, 5, 8, 15, 30),
  },
  {
    date: new Date(2020, 5, 10),
    quantity: 5.6,
    price: null,
    eventTypeName: 'Liftleie timepris',
    isExpenseType: false,
    isHoursEventType: false,
    isAdditionalHoursEventType: true,
    isWorkHour: false,
    isApproved: true,
    isRejected: false,
    tasksCount: 2,
    firstTaskStart: new Date(2020, 5, 8),
    lastTaskEnd: new Date(2020, 5, 8),
  },
  {
    date: new Date(2020, 5, 8),
    quantity: 5,
    price: null,
    eventTypeName: 'Arbeidstid',
    isExpenseType: false,
    isHoursEventType: true,
    isAdditionalHoursEventType: false,
    isWorkHour: true,
    isApproved: true,
    isRejected: false,
    tasksCount: 2,
    firstTaskStart: new Date(2020, 5, 8),
    lastTaskEnd: new Date(2020, 5, 8),
  },
  {
    date: new Date(2020, 5, 9),
    quantity: 6,
    price: null,
    eventTypeName: 'Arbeidstid',
    isExpenseType: false,
    isHoursEventType: true,
    isAdditionalHoursEventType: false,
    isWorkHour: true,
    isApproved: false,
    isRejected: false,
    tasksCount: 2,
    firstTaskStart: new Date(2020, 5, 9),
    lastTaskEnd: new Date(2020, 5, 9),
  },
  {
    date: new Date(2020, 5, 7),
    quantity: 6,
    price: null,
    eventTypeName: 'arbeidstid',
    isExpenseType: false,
    isHoursEventType: true,
    isAdditionalHoursEventType: false,
    isWorkHour: true,
    isApproved: false,
    isRejected: false,
    tasksCount: 2,
    firstTaskStart: new Date(2020, 5, 9),
    lastTaskEnd: new Date(2020, 5, 9),
  },
  {
    date: new Date(2020, 5, 7),
    quantity: 1,
    price: null,
    eventTypeName: 'Overtid 50%',
    isExpenseType: false,
    isHoursEventType: true,
    isAdditionalHoursEventType: false,
    isWorkHour: true,
    isApproved: false,
    isRejected: true,
    tasksCount: 2,
    firstTaskStart: new Date(2020, 5, 9),
    lastTaskEnd: new Date(2020, 5, 9),
  },
];
